name: CI checks for Daybreak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      babashka-ref:
        description: "Babashka ref"
        required: false

env:
  babashka-ref: ${{ inputs.babashka-ref || 'v1.3.189' }}

jobs:
  clojure:
    name: Daybreak [Clojure/Babashka implementation]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Babashka@${{ env.babashka-ref }}
        run: |
          bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/${{ env.babashka-ref }}/install)

      - name: Clean
        run: make clean

      - name: Install runtime
        run: make runtime

      - name: Build
        run: make build

      - name: Run
        run: make run

  success:
    name: Success
    runs-on: ubuntu-latest
    needs:
      - clojure
    steps:
      - run: "true"
